import type { ReportDefinition, ResourceDefinition } from './types'
import {
  bankAccountTypeOptions,
  cashFlowReferenceOptions,
  cashFlowTypeOptions,
  categoryTypeOptions,
  chartAccountNatureOptions,
  driverPaymentStatusOptions,
  driverPaymentTypeOptions,
  entryTypeOptions,
  financialStatusOptions,
  fiscalDocumentTypeOptions,
  maintenanceStatusOptions,
  maintenanceTypeOptions,
  orderStatusOptions,
  paymentMethodTypeOptions,
  reconciliationStatusOptions,
  recurrenceFrequencyOptions,
  shipmentStatusOptions,
  vehicleStatusOptions,
  vehicleTypeOptions,
} from './enums'

export const resources: ResourceDefinition[] = [
  {
    key: 'companies',
    section: 'admin',
    title: 'Empresas',
    subtitle: 'Gestão de empresas vinculadas ao tenant',
    routePath: '/app/admin/companies',
    icon: 'mdi-office-building-outline',
    basePath: '/companies',
    permissions: {
      read: 'companies.read',
      create: 'companies.create',
      update: 'companies.update',
      remove: 'companies.delete',
    },
    columns: [
      { key: 'name', title: 'Nome', path: 'name' },
      { key: 'cnpj', title: 'CNPJ', path: 'cnpj' },
      { key: 'email', title: 'E-mail', path: 'email' },
      { key: 'status', title: 'Status', path: 'status', type: 'status' },
    ],
    filters: [
      { key: 'page', label: 'Página', type: 'text' },
      { key: 'limit', label: 'Limite', type: 'text' },
    ],
    fields: [
      { key: 'name', label: 'Nome', type: 'text', required: true },
      { key: 'tradeName', label: 'Nome Fantasia', type: 'text' },
      { key: 'cnpj', label: 'CNPJ', type: 'text', required: true },
      { key: 'email', label: 'E-mail', type: 'text' },
      { key: 'phone', label: 'Telefone', type: 'text' },
      { key: 'website', label: 'Website', type: 'text' },
      { key: 'logoUrl', label: 'URL da logo', type: 'text' },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        options: [
          { label: 'ACTIVE', value: 'ACTIVE' },
          { label: 'INACTIVE', value: 'INACTIVE' },
        ],
      },
    ],
  },
  {
    key: 'users',
    section: 'admin',
    title: 'Usuários',
    subtitle: 'Ciclo de vida de acesso de usuários',
    routePath: '/app/admin/users',
    icon: 'mdi-account-group-outline',
    basePath: '/users',
    permissions: {
      read: 'users.read',
      create: 'users.create',
      update: 'users.update',
      remove: 'users.delete',
    },
    columns: [
      { key: 'name', title: 'Nome', path: 'name' },
      { key: 'email', title: 'E-mail', path: 'email' },
      { key: 'isActive', title: 'Ativo', path: 'isActive', type: 'boolean' },
      { key: 'createdAt', title: 'Criado em', path: 'createdAt', type: 'datetime' },
    ],
    fields: [
      { key: 'name', label: 'Nome', type: 'text', required: true },
      { key: 'email', label: 'E-mail', type: 'text', required: true },
      { key: 'password', label: 'Senha', type: 'password' },
      { key: 'isActive', label: 'Ativo', type: 'switch' },
    ],
  },
  {
    key: 'roles',
    section: 'admin',
    title: 'Roles',
    subtitle: 'Perfis de acesso e permissões',
    routePath: '/app/admin/roles',
    icon: 'mdi-shield-account-outline',
    basePath: '/roles',
    permissions: {
      read: 'roles.read',
      create: 'roles.manage',
      update: 'roles.manage',
      remove: 'roles.manage',
    },
    columns: [
      { key: 'name', title: 'Nome', path: 'name' },
      { key: 'description', title: 'Descrição', path: 'description' },
      { key: 'isSystem', title: 'Sistema', path: 'isSystem', type: 'boolean' },
    ],
    fields: [
      { key: 'name', label: 'Nome', type: 'text', required: true },
      { key: 'description', label: 'Descrição', type: 'textarea' },
      {
        key: 'permissionIds',
        label: 'Permissões',
        type: 'select',
        optionSource: {
          endpoint: '/permissions',
          labelKey: 'code',
          valueKey: 'id',
          query: { limit: 100 },
        },
      },
    ],
  },
  {
    key: 'permissions',
    section: 'admin',
    title: 'Permissões',
    subtitle: 'Permissões customizadas por tenant',
    routePath: '/app/admin/permissions',
    icon: 'mdi-shield-key-outline',
    basePath: '/permissions',
    permissions: {
      read: 'permissions.read',
      create: 'permissions.manage',
      update: 'permissions.manage',
      remove: 'permissions.manage',
    },
    columns: [
      { key: 'code', title: 'Código', path: 'code' },
      { key: 'module', title: 'Módulo', path: 'module' },
      { key: 'description', title: 'Descrição', path: 'description' },
    ],
    fields: [
      { key: 'code', label: 'Código', type: 'text', required: true },
      { key: 'module', label: 'Módulo', type: 'text' },
      { key: 'description', label: 'Descrição', type: 'textarea' },
    ],
  },
  {
    key: 'user-roles',
    section: 'admin',
    title: 'Vínculo Usuário x Role',
    subtitle: 'Associação de usuários aos perfis',
    routePath: '/app/admin/user-roles',
    icon: 'mdi-account-switch-outline',
    basePath: '/user-roles',
    permissions: {
      read: 'roles.read',
      create: 'roles.manage',
      update: 'roles.manage',
      remove: 'roles.manage',
    },
    hideEdit: true,
    columns: [
      { key: 'userId', title: 'Usuário', path: 'userId' },
      { key: 'roleId', title: 'Role', path: 'roleId' },
      { key: 'createdAt', title: 'Criado em', path: 'createdAt', type: 'datetime' },
    ],
    fields: [
      {
        key: 'userId',
        label: 'Usuário',
        type: 'select',
        required: true,
        optionSource: {
          endpoint: '/users',
          labelKey: 'email',
          valueKey: 'id',
          query: { limit: 100 },
        },
      },
      {
        key: 'roleId',
        label: 'Role',
        type: 'select',
        required: true,
        optionSource: {
          endpoint: '/roles',
          labelKey: 'name',
          valueKey: 'id',
          query: { limit: 100 },
        },
      },
    ],
  },
  {
    key: 'units',
    section: 'admin',
    title: 'Unidades',
    subtitle: 'Cadastro de unidade operacional (create-only)',
    routePath: '/app/admin/units',
    icon: 'mdi-warehouse',
    basePath: '/units',
    permissions: {
      read: 'units.create',
      create: 'units.create',
    },
    listDisabled: true,
    hideEdit: true,
    hideDelete: true,
    columns: [
      { key: 'name', title: 'Nome', path: 'name' },
      { key: 'address', title: 'Endereço', path: 'address' },
      { key: 'createdAt', title: 'Criado em', path: 'createdAt', type: 'datetime' },
    ],
    fields: [
      { key: 'name', label: 'Nome da unidade', type: 'text', required: true },
      { key: 'address', label: 'Endereço', type: 'textarea', required: true },
    ],
  },
  {
    key: 'audit-logs',
    section: 'admin',
    title: 'Auditoria',
    subtitle: 'Rastreabilidade de ações do tenant',
    routePath: '/app/admin/audit',
    icon: 'mdi-history',
    basePath: '/audit/logs',
    permissions: {
      read: 'audit.logs.read',
    },
    hideCreate: true,
    hideEdit: true,
    hideDelete: true,
    columns: [
      { key: 'createdAt', title: 'Data', path: 'createdAt', type: 'datetime' },
      { key: 'action', title: 'Ação', path: 'action', type: 'status' },
      { key: 'entityName', title: 'Entidade', path: 'entityName' },
      { key: 'userEmail', title: 'Usuário', path: 'userEmail' },
      { key: 'requestPath', title: 'Endpoint', path: 'requestPath' },
    ],
    filters: [
      { key: 'entityName', label: 'Entidade', type: 'text' },
      { key: 'entityId', label: 'ID Entidade', type: 'text' },
      { key: 'action', label: 'Ação', type: 'text' },
      { key: 'userId', label: 'ID Usuário', type: 'text' },
      { key: 'from', label: 'De', type: 'date' },
      { key: 'to', label: 'Até', type: 'date' },
    ],
    fields: [],
  },
  {
    key: 'drivers',
    section: 'operations',
    title: 'Motoristas',
    subtitle: 'Gestão de motoristas',
    routePath: '/app/operations/drivers',
    icon: 'mdi-account-tie-hat-outline',
    basePath: '/drivers',
    moduleAccess: 'fleet',
    permissions: {
      read: 'drivers.read',
      create: 'drivers.create',
      update: 'drivers.update',
      remove: 'drivers.delete',
    },
    columns: [
      { key: 'name', title: 'Nome', path: 'name' },
      { key: 'documentNumber', title: 'Documento', path: 'documentNumber' },
      { key: 'email', title: 'E-mail', path: 'email' },
      {
        key: 'paymentCalculationType',
        title: 'Cálculo',
        path: 'paymentCalculationType',
        type: 'status',
      },
      { key: 'isActive', title: 'Ativo', path: 'isActive', type: 'boolean' },
    ],
    filters: [{ key: 'search', label: 'Busca', type: 'text' }],
    fields: [
      { key: 'name', label: 'Nome', type: 'text', required: true },
      { key: 'documentNumber', label: 'Documento', type: 'text' },
      { key: 'phone', label: 'Telefone', type: 'text' },
      { key: 'email', label: 'E-mail', type: 'text' },
      { key: 'isActive', label: 'Ativo', type: 'switch' },
      {
        key: 'paymentCalculationType',
        label: 'Tipo de cálculo',
        type: 'select',
        options: driverPaymentTypeOptions,
      },
      { key: 'paymentRate', label: 'Taxa', type: 'number', step: 0.01, min: 0 },
      {
        key: 'defaultPaymentStatus',
        label: 'Status padrão de pagamento',
        type: 'select',
        options: driverPaymentStatusOptions,
      },
    ],
  },
  {
    key: 'driver-payments',
    section: 'operations',
    title: 'Pagamentos de Motorista',
    subtitle: 'Controle de pagamentos da frota',
    routePath: '/app/operations/driver-payments',
    icon: 'mdi-cash-fast',
    basePath: '/driver-payments',
    moduleAccess: 'fleet',
    permissions: {
      read: 'driver-payments.read',
      create: 'driver-payments.create',
      update: 'driver-payments.update',
      remove: 'driver-payments.delete',
    },
    columns: [
      { key: 'driverId', title: 'Motorista', path: 'driverId' },
      { key: 'amount', title: 'Valor', path: 'amount', type: 'money' },
      { key: 'status', title: 'Status', path: 'status', type: 'status' },
      { key: 'dueDate', title: 'Vencimento', path: 'dueDate', type: 'date' },
    ],
    filters: [
      { key: 'driverId', label: 'Motorista', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: driverPaymentStatusOptions },
    ],
    fields: [
      { key: 'driverId', label: 'Motorista ID', type: 'text', required: true },
      { key: 'shipmentId', label: 'Shipment ID', type: 'text' },
      { key: 'amount', label: 'Valor', type: 'number', required: true, min: 0.01 },
      {
        key: 'calculationType',
        label: 'Tipo de cálculo',
        type: 'select',
        required: true,
        options: driverPaymentTypeOptions,
      },
      { key: 'status', label: 'Status', type: 'select', options: driverPaymentStatusOptions },
      { key: 'dueDate', label: 'Data de vencimento', type: 'date' },
      { key: 'notes', label: 'Observações', type: 'textarea' },
    ],
    customActions: [
      {
        id: 'pay-driver-payment',
        label: 'Pagar',
        method: 'POST',
        path: '/driver-payments/:id/pay',
        permission: 'driver-payments.pay',
        color: 'success',
        icon: 'mdi-cash-check',
        confirmMessage: 'Confirmar quitação do pagamento do motorista?',
        fields: [
          { key: 'paidAt', label: 'Data de pagamento', type: 'datetime' },
          { key: 'notes', label: 'Observações', type: 'textarea' },
        ],
      },
    ],
  },
  {
    key: 'vehicles',
    section: 'operations',
    title: 'Veículos',
    subtitle: 'Gestão de veículos da frota',
    routePath: '/app/operations/vehicles',
    icon: 'mdi-truck-outline',
    basePath: '/vehicles',
    moduleAccess: 'fleet',
    permissions: {
      read: 'vehicles.read',
      create: 'vehicles.create',
      update: 'vehicles.update',
      remove: 'vehicles.delete',
    },
    columns: [
      { key: 'plate', title: 'Placa', path: 'plate' },
      { key: 'brand', title: 'Marca', path: 'brand' },
      { key: 'model', title: 'Modelo', path: 'model' },
      { key: 'vehicleType', title: 'Tipo', path: 'vehicleType', type: 'status' },
      { key: 'status', title: 'Status', path: 'status', type: 'status' },
    ],
    filters: [
      { key: 'search', label: 'Busca', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: vehicleStatusOptions },
      { key: 'vehicleType', label: 'Tipo', type: 'select', options: vehicleTypeOptions },
    ],
    fields: [
      { key: 'plate', label: 'Placa', type: 'text', required: true },
      { key: 'brand', label: 'Marca', type: 'text', required: true },
      { key: 'model', label: 'Modelo', type: 'text', required: true },
      { key: 'year', label: 'Ano', type: 'number', required: true, min: 1900, max: 2100 },
      { key: 'capacityKg', label: 'Capacidade KG', type: 'number', required: true, min: 0.01 },
      {
        key: 'vehicleType',
        label: 'Tipo de veículo',
        type: 'select',
        required: true,
        options: vehicleTypeOptions,
      },
      { key: 'status', label: 'Status', type: 'select', options: vehicleStatusOptions },
    ],
  },
  {
    key: 'vehicle-maintenance',
    section: 'operations',
    title: 'Manutenção de Veículos',
    subtitle: 'Agendamento e execução de manutenção',
    routePath: '/app/operations/vehicle-maintenance',
    icon: 'mdi-wrench-clock-outline',
    basePath: '/vehicle-maintenance',
    moduleAccess: 'fleet',
    permissions: {
      read: 'vehicle-maintenance.read',
      create: 'vehicle-maintenance.create',
      update: 'vehicle-maintenance.update',
      remove: 'vehicle-maintenance.delete',
    },
    columns: [
      { key: 'vehicleId', title: 'Veículo ID', path: 'vehicleId' },
      { key: 'type', title: 'Tipo', path: 'type', type: 'status' },
      { key: 'cost', title: 'Custo', path: 'cost', type: 'money' },
      { key: 'maintenanceDate', title: 'Data', path: 'maintenanceDate', type: 'date' },
      { key: 'status', title: 'Status', path: 'status', type: 'status' },
    ],
    filters: [
      { key: 'vehicleId', label: 'Veículo', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: maintenanceStatusOptions },
    ],
    fields: [
      { key: 'vehicleId', label: 'Veículo ID', type: 'text', required: true },
      {
        key: 'type',
        label: 'Tipo',
        type: 'select',
        required: true,
        options: maintenanceTypeOptions,
      },
      { key: 'description', label: 'Descrição', type: 'textarea', required: true },
      { key: 'cost', label: 'Custo', type: 'number', required: true, min: 0.01 },
      { key: 'maintenanceDate', label: 'Data de manutenção', type: 'date', required: true },
      { key: 'nextMaintenanceDate', label: 'Próxima manutenção', type: 'date' },
      { key: 'status', label: 'Status', type: 'select', options: maintenanceStatusOptions },
    ],
    customActions: [
      {
        id: 'complete-maintenance',
        label: 'Concluir',
        method: 'POST',
        path: '/vehicle-maintenance/:id/complete',
        permission: 'vehicle-maintenance.complete',
        color: 'success',
        icon: 'mdi-check-decagram',
        confirmMessage: 'Concluir manutenção? Pode gerar conta a pagar automaticamente.',
        fields: [
          { key: 'autoGenerateAccountsPayable', label: 'Gerar AP automática', type: 'switch' },
          { key: 'payableDueDate', label: 'Vencimento AP', type: 'date' },
          { key: 'payableDescription', label: 'Descrição AP', type: 'text' },
          { key: 'supplierId', label: 'Fornecedor ID', type: 'text' },
          { key: 'costCenterId', label: 'Centro de custo ID', type: 'text' },
          { key: 'categoryId', label: 'Categoria ID', type: 'text' },
          { key: 'paymentMethodId', label: 'Forma pagamento ID', type: 'text' },
        ],
      },
    ],
  },
  {
    key: 'orders',
    section: 'operations',
    title: 'Pedidos',
    subtitle: 'Pedidos operacionais',
    routePath: '/app/operations/orders',
    icon: 'mdi-clipboard-list-outline',
    basePath: '/orders',
    moduleAccess: 'logistics',
    permissions: {
      read: 'orders.read',
      create: 'orders.create',
      update: 'orders.update',
      remove: 'orders.delete',
    },
    columns: [
      { key: 'orderNumber', title: 'Pedido', path: 'orderNumber' },
      { key: 'customerId', title: 'Cliente ID', path: 'customerId' },
      { key: 'totalValue', title: 'Valor', path: 'totalValue', type: 'money' },
      { key: 'status', title: 'Status', path: 'status', type: 'status' },
    ],
    filters: [
      { key: 'orderNumber', label: 'Pedido', type: 'text' },
      { key: 'customerId', label: 'Cliente', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: orderStatusOptions },
    ],
    fields: [
      { key: 'orderNumber', label: 'Número', type: 'text', required: true },
      { key: 'customerId', label: 'Cliente ID', type: 'text', required: true },
      { key: 'totalValue', label: 'Valor total', type: 'number', required: true, min: 0.01 },
      { key: 'description', label: 'Descrição', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: orderStatusOptions },
    ],
    customActions: [
      {
        id: 'close-order',
        label: 'Fechar',
        method: 'POST',
        path: '/orders/:id/close',
        permission: 'orders.close',
        color: 'warning',
        icon: 'mdi-lock-check-outline',
        confirmMessage: 'Fechar pedido? Todos os shipments precisam estar DELIVERED.',
      },
    ],
  },
  {
    key: 'routes',
    section: 'operations',
    title: 'Rotas',
    subtitle: 'Gestão de rotas logísticas',
    routePath: '/app/operations/routes',
    icon: 'mdi-map-marker-path',
    basePath: '/routes',
    moduleAccess: 'logistics',
    permissions: {
      read: 'routes.read',
      create: 'routes.create',
      update: 'routes.update',
      remove: 'routes.delete',
    },
    columns: [
      { key: 'name', title: 'Rota', path: 'name' },
      { key: 'origin', title: 'Origem', path: 'origin' },
      { key: 'destination', title: 'Destino', path: 'destination' },
      { key: 'estimatedDistanceKm', title: 'Distância', path: 'estimatedDistanceKm' },
    ],
    filters: [{ key: 'search', label: 'Busca', type: 'text' }],
    fields: [
      { key: 'name', label: 'Nome', type: 'text', required: true },
      { key: 'origin', label: 'Origem', type: 'text', required: true },
      { key: 'destination', label: 'Destino', type: 'text', required: true },
      {
        key: 'estimatedDistanceKm',
        label: 'Distância KM',
        type: 'number',
        required: true,
        min: 0.01,
      },
      {
        key: 'estimatedDurationMinutes',
        label: 'Duração minutos',
        type: 'number',
        required: true,
        min: 1,
      },
    ],
  },
  {
    key: 'route-stops',
    section: 'operations',
    title: 'Paradas de Rota',
    subtitle: 'Gerenciar paradas por rota',
    routePath: '/app/operations/routes/:routeId/stops',
    icon: 'mdi-map-marker-multiple-outline',
    basePath: '/routes/:routeId/stops',
    moduleAccess: 'logistics',
    permissions: {
      read: 'route-stops.read',
      create: 'route-stops.create',
      update: 'route-stops.update',
      remove: 'route-stops.delete',
    },
    columns: [
      { key: 'sequence', title: 'Sequência', path: 'sequence' },
      { key: 'address', title: 'Endereço', path: 'address' },
      { key: 'estimatedArrivalTime', title: 'Chegada estimada', path: 'estimatedArrivalTime' },
    ],
    fields: [
      { key: 'address', label: 'Endereço', type: 'textarea', required: true },
      { key: 'sequence', label: 'Sequência', type: 'number', required: true, min: 1 },
      { key: 'estimatedArrivalTime', label: 'Hora estimada (HH:mm:ss)', type: 'text' },
    ],
    filters: [],
  },
  {
    key: 'freight-tables',
    section: 'operations',
    title: 'Tabelas de Frete',
    subtitle: 'Parâmetros de frete',
    routePath: '/app/operations/freight-tables',
    icon: 'mdi-table-cog',
    basePath: '/freight-tables',
    moduleAccess: 'logistics',
    permissions: {
      read: 'freight-tables.read',
      create: 'freight-tables.create',
      update: 'freight-tables.update',
      remove: 'freight-tables.delete',
    },
    columns: [
      { key: 'region', title: 'Região', path: 'region' },
      { key: 'vehicleType', title: 'Tipo veículo', path: 'vehicleType', type: 'status' },
      { key: 'pricePerKm', title: 'Preço/KM', path: 'pricePerKm', type: 'money' },
      { key: 'minimumFreightValue', title: 'Mínimo', path: 'minimumFreightValue', type: 'money' },
    ],
    filters: [
      { key: 'region', label: 'Região', type: 'text' },
      { key: 'vehicleType', label: 'Tipo', type: 'select', options: vehicleTypeOptions },
    ],
    fields: [
      { key: 'region', label: 'Região', type: 'text', required: true },
      {
        key: 'vehicleType',
        label: 'Tipo veículo',
        type: 'select',
        required: true,
        options: vehicleTypeOptions,
      },
      { key: 'pricePerKm', label: 'Preço por KM', type: 'number', required: true, min: 0 },
      { key: 'minimumFreightValue', label: 'Frete mínimo', type: 'number', required: true, min: 0 },
      { key: 'pricePerKg', label: 'Preço por KG', type: 'number', min: 0 },
    ],
  },
  {
    key: 'shipments',
    section: 'operations',
    title: 'Shipments',
    subtitle: 'Expedição e status operacional',
    routePath: '/app/operations/shipments',
    icon: 'mdi-truck-delivery-outline',
    basePath: '/shipments',
    moduleAccess: 'logistics',
    permissions: {
      read: 'shipments.read',
      create: 'shipments.create',
      update: 'shipments.update',
      remove: 'shipments.delete',
    },
    columns: [
      { key: 'orderId', title: 'Pedido ID', path: 'orderId' },
      { key: 'driverId', title: 'Motorista ID', path: 'driverId' },
      { key: 'vehicleId', title: 'Veículo ID', path: 'vehicleId' },
      { key: 'freightValue', title: 'Frete', path: 'freightValue', type: 'money' },
      { key: 'status', title: 'Status', path: 'status', type: 'status' },
    ],
    filters: [
      { key: 'orderId', label: 'Pedido', type: 'text' },
      { key: 'driverId', label: 'Motorista', type: 'text' },
      { key: 'vehicleId', label: 'Veículo', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: shipmentStatusOptions },
    ],
    fields: [
      { key: 'orderId', label: 'Pedido ID', type: 'text', required: true },
      { key: 'driverId', label: 'Motorista ID', type: 'text' },
      { key: 'vehicleId', label: 'Veículo ID', type: 'text' },
      { key: 'routeId', label: 'Rota ID', type: 'text' },
      { key: 'freightTableId', label: 'Tabela de frete ID', type: 'text' },
      { key: 'freightValue', label: 'Frete', type: 'number', min: 0 },
      { key: 'cargoWeightKg', label: 'Peso KG', type: 'number', min: 0 },
      { key: 'departureDate', label: 'Saída', type: 'datetime' },
      { key: 'deliveryDate', label: 'Entrega', type: 'datetime' },
      { key: 'status', label: 'Status', type: 'select', options: shipmentStatusOptions },
    ],
    customActions: [
      {
        id: 'shipment-status',
        label: 'Atualizar status',
        method: 'PATCH',
        path: '/shipments/:id/status',
        permission: 'shipments.update-status',
        color: 'info',
        icon: 'mdi-progress-clock',
        fields: [
          {
            key: 'status',
            label: 'Status',
            type: 'select',
            required: true,
            options: shipmentStatusOptions,
          },
          { key: 'deliveryDate', label: 'Data de entrega', type: 'datetime' },
        ],
      },
    ],
  },
  {
    key: 'fiscal-documents',
    section: 'operations',
    title: 'Documentos Fiscais',
    subtitle: 'Gestão de CTe/NFe/MDFe',
    routePath: '/app/operations/fiscal-documents',
    icon: 'mdi-file-document-outline',
    basePath: '/fiscal/documents',
    permissions: {
      read: 'fiscal.read',
      create: 'fiscal.create',
      update: 'fiscal.update',
      remove: 'fiscal.delete',
    },
    columns: [
      { key: 'shipmentId', title: 'Shipment ID', path: 'shipmentId' },
      { key: 'documentType', title: 'Tipo', path: 'documentType', type: 'status' },
      { key: 'accessKey', title: 'Chave de acesso', path: 'accessKey' },
      { key: 'issueDate', title: 'Emissão', path: 'issueDate', type: 'date' },
    ],
    filters: [
      { key: 'shipmentId', label: 'Shipment', type: 'text' },
      { key: 'documentType', label: 'Tipo', type: 'select', options: fiscalDocumentTypeOptions },
      { key: 'accessKey', label: 'Chave acesso', type: 'text' },
    ],
    fields: [
      { key: 'shipmentId', label: 'Shipment ID', type: 'text', required: true },
      {
        key: 'documentType',
        label: 'Tipo documento',
        type: 'select',
        required: true,
        options: fiscalDocumentTypeOptions,
      },
      { key: 'accessKey', label: 'Chave de acesso (44 dígitos)', type: 'text', required: true },
      { key: 'xmlUrl', label: 'URL XML', type: 'text' },
      { key: 'issueDate', label: 'Data emissão', type: 'date' },
      { key: 'notes', label: 'Observações', type: 'textarea' },
    ],
  },
  {
    key: 'accounts-payable',
    section: 'financial',
    title: 'Contas a Pagar',
    subtitle: 'Lançamento, pagamento, recorrência e anexos',
    routePath: '/app/financial/accounts-payable',
    icon: 'mdi-cash-minus',
    basePath: '/financial/accounts-payable',
    moduleAccess: 'financial',
    permissions: {
      read: 'financial.read',
      create: 'financial.create',
      update: 'financial.update',
      remove: 'financial.cancel',
    },
    columns: [
      { key: 'description', title: 'Descrição', path: 'description' },
      { key: 'amount', title: 'Valor', path: 'amount', type: 'money' },
      { key: 'dueDate', title: 'Vencimento', path: 'dueDate', type: 'date' },
      { key: 'status', title: 'Status', path: 'status', type: 'status' },
      { key: 'paidAmount', title: 'Pago', path: 'paidAmount', type: 'money' },
    ],
    filters: [
      { key: 'from', label: 'De', type: 'date' },
      { key: 'to', label: 'Até', type: 'date' },
      { key: 'status', label: 'Status', type: 'select', options: financialStatusOptions },
      { key: 'costCenterId', label: 'Centro de custo', type: 'text' },
    ],
    fields: [
      { key: 'documentNumber', label: 'Documento', type: 'text' },
      { key: 'description', label: 'Descrição', type: 'textarea', required: true },
      { key: 'supplierId', label: 'Fornecedor ID', type: 'text' },
      { key: 'costCenterId', label: 'Centro de custo ID', type: 'text' },
      { key: 'categoryId', label: 'Categoria ID', type: 'text' },
      { key: 'paymentMethodId', label: 'Forma pagamento ID', type: 'text' },
      { key: 'chartAccountId', label: 'Conta contábil ID', type: 'text' },
      { key: 'recurrenceRuleId', label: 'Regra recorrência ID', type: 'text' },
      { key: 'interestFineRuleId', label: 'Regra juros/multa ID', type: 'text' },
      { key: 'issueDate', label: 'Emissão', type: 'date', required: true },
      { key: 'dueDate', label: 'Vencimento', type: 'date', required: true },
      { key: 'amount', label: 'Valor', type: 'number', required: true, min: 0.01 },
      { key: 'installmentCount', label: 'Parcelas', type: 'number', min: 1, max: 60 },
      { key: 'notes', label: 'Observações', type: 'textarea' },
    ],
    customActions: [
      {
        id: 'pay-ap',
        label: 'Pagar',
        method: 'POST',
        path: '/financial/accounts-payable/:id/pay',
        permission: 'financial.pay',
        color: 'success',
        icon: 'mdi-cash-check',
        fields: [
          { key: 'amount', label: 'Valor pago', type: 'number', required: true, min: 0.01 },
          { key: 'paymentDate', label: 'Data pagamento', type: 'date' },
          { key: 'bankAccountId', label: 'Conta bancária ID', type: 'text', required: true },
          { key: 'manualInterest', label: 'Juros manual', type: 'number', min: 0 },
          { key: 'manualFine', label: 'Multa manual', type: 'number', min: 0 },
          { key: 'discountAmount', label: 'Desconto', type: 'number', min: 0 },
          { key: 'applyAutoCharges', label: 'Aplicar juros/multa automático', type: 'switch' },
        ],
      },
      {
        id: 'generate-ap-recurrence',
        label: 'Gerar recorrência',
        method: 'POST',
        path: '/financial/accounts-payable/:id/recurrence/generate',
        permission: 'financial.recurrence.generate',
        icon: 'mdi-repeat',
        fields: [
          {
            key: 'occurrences',
            label: 'Ocorrências',
            type: 'number',
            required: true,
            min: 1,
            max: 120,
          },
        ],
      },
    ],
    attachments: {
      listPath: '/financial/accounts-payable/:id/attachments',
      createPath: '/financial/accounts-payable/:id/attachments',
      permissionRead: 'financial.attachments.read',
      permissionCreate: 'financial.attachments.create',
    },
  },
  {
    key: 'accounts-receivable',
    section: 'financial',
    title: 'Contas a Receber',
    subtitle: 'Lançamento, recebimento, recorrência e anexos',
    routePath: '/app/financial/accounts-receivable',
    icon: 'mdi-cash-plus',
    basePath: '/financial/accounts-receivable',
    moduleAccess: 'financial',
    permissions: {
      read: 'financial.read',
      create: 'financial.create',
      update: 'financial.update',
      remove: 'financial.cancel',
    },
    columns: [
      { key: 'description', title: 'Descrição', path: 'description' },
      { key: 'amount', title: 'Valor', path: 'amount', type: 'money' },
      { key: 'dueDate', title: 'Vencimento', path: 'dueDate', type: 'date' },
      { key: 'status', title: 'Status', path: 'status', type: 'status' },
      { key: 'receivedAmount', title: 'Recebido', path: 'receivedAmount', type: 'money' },
    ],
    filters: [
      { key: 'from', label: 'De', type: 'date' },
      { key: 'to', label: 'Até', type: 'date' },
      { key: 'status', label: 'Status', type: 'select', options: financialStatusOptions },
      { key: 'costCenterId', label: 'Centro de custo', type: 'text' },
    ],
    fields: [
      { key: 'documentNumber', label: 'Documento', type: 'text' },
      { key: 'description', label: 'Descrição', type: 'textarea', required: true },
      { key: 'customerId', label: 'Cliente ID', type: 'text' },
      { key: 'costCenterId', label: 'Centro de custo ID', type: 'text' },
      { key: 'categoryId', label: 'Categoria ID', type: 'text' },
      { key: 'paymentMethodId', label: 'Forma pagamento ID', type: 'text' },
      { key: 'chartAccountId', label: 'Conta contábil ID', type: 'text' },
      { key: 'recurrenceRuleId', label: 'Regra recorrência ID', type: 'text' },
      { key: 'interestFineRuleId', label: 'Regra juros/multa ID', type: 'text' },
      { key: 'issueDate', label: 'Emissão', type: 'date', required: true },
      { key: 'dueDate', label: 'Vencimento', type: 'date', required: true },
      { key: 'amount', label: 'Valor', type: 'number', required: true, min: 0.01 },
      { key: 'installmentCount', label: 'Parcelas', type: 'number', min: 1, max: 60 },
      { key: 'notes', label: 'Observações', type: 'textarea' },
    ],
    customActions: [
      {
        id: 'receive-ar',
        label: 'Receber',
        method: 'POST',
        path: '/financial/accounts-receivable/:id/receive',
        permission: 'financial.receive',
        color: 'success',
        icon: 'mdi-cash-check',
        fields: [
          { key: 'amount', label: 'Valor recebido', type: 'number', required: true, min: 0.01 },
          { key: 'receiptDate', label: 'Data recebimento', type: 'date' },
          { key: 'bankAccountId', label: 'Conta bancária ID', type: 'text', required: true },
          { key: 'manualInterest', label: 'Juros manual', type: 'number', min: 0 },
          { key: 'manualFine', label: 'Multa manual', type: 'number', min: 0 },
          { key: 'discountAmount', label: 'Desconto', type: 'number', min: 0 },
          { key: 'applyAutoCharges', label: 'Aplicar juros/multa automático', type: 'switch' },
        ],
      },
      {
        id: 'generate-ar-recurrence',
        label: 'Gerar recorrência',
        method: 'POST',
        path: '/financial/accounts-receivable/:id/recurrence/generate',
        permission: 'financial.recurrence.generate',
        icon: 'mdi-repeat',
        fields: [
          {
            key: 'occurrences',
            label: 'Ocorrências',
            type: 'number',
            required: true,
            min: 1,
            max: 120,
          },
        ],
      },
    ],
    attachments: {
      listPath: '/financial/accounts-receivable/:id/attachments',
      createPath: '/financial/accounts-receivable/:id/attachments',
      permissionRead: 'financial.attachments.read',
      permissionCreate: 'financial.attachments.create',
    },
  },
  {
    key: 'bank-accounts',
    section: 'financial',
    title: 'Contas Bancárias',
    subtitle: 'Gestão de contas e saldo',
    routePath: '/app/financial/bank-accounts',
    icon: 'mdi-bank-outline',
    basePath: '/financial/bank-accounts',
    moduleAccess: 'financial',
    permissions: {
      read: 'financial.bank-accounts.read',
      create: 'financial.bank-accounts.create',
      update: 'financial.bank-accounts.update',
      remove: 'financial.bank-accounts.delete',
    },
    columns: [
      { key: 'bankName', title: 'Banco', path: 'bankName' },
      { key: 'accountNumber', title: 'Conta', path: 'accountNumber' },
      { key: 'agency', title: 'Agência', path: 'agency' },
      { key: 'currentBalance', title: 'Saldo', path: 'currentBalance', type: 'money' },
      { key: 'isDefault', title: 'Default', path: 'isDefault', type: 'boolean' },
    ],
    fields: [
      { key: 'bankName', label: 'Banco', type: 'text', required: true },
      { key: 'accountNumber', label: 'Número da conta', type: 'text', required: true },
      { key: 'agency', label: 'Agência', type: 'text', required: true },
      {
        key: 'accountType',
        label: 'Tipo',
        type: 'select',
        required: true,
        options: bankAccountTypeOptions,
      },
      { key: 'currentBalance', label: 'Saldo atual', type: 'number' },
      { key: 'isDefault', label: 'Conta padrão', type: 'switch' },
    ],
    customActions: [
      {
        id: 'adjust-balance',
        label: 'Ajustar saldo',
        method: 'POST',
        path: '/financial/bank-accounts/:id/adjust-balance',
        permission: 'financial.bank-accounts.adjust-balance',
        color: 'warning',
        icon: 'mdi-scale-balance',
        fields: [
          { key: 'amount', label: 'Valor', type: 'number', required: true, min: 0.01 },
          { key: 'isCredit', label: 'Crédito', type: 'switch' },
          { key: 'description', label: 'Descrição', type: 'text' },
        ],
      },
    ],
  },
  {
    key: 'reconciliation',
    section: 'financial',
    title: 'Conciliação Bancária',
    subtitle: 'Conciliação e divergências',
    routePath: '/app/financial/reconciliation',
    icon: 'mdi-file-compare',
    basePath: '/financial/reconciliation',
    moduleAccess: 'financial',
    permissions: {
      read: 'financial.reconciliation.read',
      create: 'financial.reconciliation.create',
      update: 'financial.reconciliation.update',
      remove: 'financial.reconciliation.execute',
    },
    hideDelete: true,
    columns: [
      { key: 'statementReference', title: 'Extrato', path: 'statementReference' },
      { key: 'bankAccountName', title: 'Conta', path: 'bankAccountName' },
      { key: 'amount', title: 'Valor', path: 'amount', type: 'money' },
      { key: 'statementDate', title: 'Data', path: 'statementDate', type: 'date' },
      { key: 'status', title: 'Status', path: 'status', type: 'status' },
    ],
    filters: [
      { key: 'status', label: 'Status', type: 'select', options: reconciliationStatusOptions },
    ],
    fields: [
      { key: 'bankAccountName', label: 'Conta bancária', type: 'text', required: true },
      { key: 'statementReference', label: 'Referência extrato', type: 'text', required: true },
      { key: 'statementDate', label: 'Data extrato', type: 'date', required: true },
      { key: 'amount', label: 'Valor', type: 'number', required: true, min: 0.01 },
      { key: 'entryType', label: 'Tipo lançamento', type: 'select', options: entryTypeOptions },
      { key: 'entryId', label: 'Lançamento ID', type: 'text' },
      { key: 'notes', label: 'Observações', type: 'textarea' },
    ],
    customActions: [
      {
        id: 'reconcile',
        label: 'Conciliar',
        method: 'POST',
        path: '/financial/reconciliation/:id/reconcile',
        permission: 'financial.reconciliation.execute',
        color: 'success',
        icon: 'mdi-check-circle-outline',
        fields: [
          {
            key: 'entryType',
            label: 'Tipo lançamento',
            type: 'select',
            required: true,
            options: entryTypeOptions,
          },
          { key: 'entryId', label: 'Lançamento ID', type: 'text', required: true },
          { key: 'notes', label: 'Observações', type: 'textarea' },
        ],
      },
      {
        id: 'mark-divergent',
        label: 'Marcar divergente',
        method: 'POST',
        path: '/financial/reconciliation/:id/mark-divergent',
        permission: 'financial.reconciliation.execute',
        color: 'error',
        icon: 'mdi-alert-circle-outline',
        fields: [{ key: 'notes', label: 'Motivo', type: 'textarea' }],
      },
    ],
  },
  {
    key: 'cash-flow',
    section: 'financial',
    title: 'Fluxo de Caixa',
    subtitle: 'Movimentações de entrada e saída',
    routePath: '/app/financial/cash-flow',
    icon: 'mdi-finance',
    basePath: '/financial/cash-flow',
    moduleAccess: 'financial',
    permissions: {
      read: 'financial.cash-flow.read',
      create: 'financial.cash-flow.create',
    },
    hideEdit: true,
    hideDelete: true,
    columns: [
      { key: 'date', title: 'Data', path: 'date', type: 'datetime' },
      { key: 'type', title: 'Tipo', path: 'type', type: 'status' },
      { key: 'amount', title: 'Valor', path: 'amount', type: 'money' },
      { key: 'referenceType', title: 'Referência', path: 'referenceType', type: 'status' },
      { key: 'bankAccountId', title: 'Conta', path: 'bankAccountId' },
    ],
    filters: [
      { key: 'type', label: 'Tipo', type: 'select', options: cashFlowTypeOptions },
      {
        key: 'referenceType',
        label: 'Referência',
        type: 'select',
        options: cashFlowReferenceOptions,
      },
      { key: 'bankAccountId', label: 'Conta', type: 'text' },
      { key: 'from', label: 'De', type: 'date' },
      { key: 'to', label: 'Até', type: 'date' },
    ],
    fields: [
      { key: 'bankAccountId', label: 'Conta bancária ID', type: 'text', required: true },
      {
        key: 'referenceType',
        label: 'Tipo referência',
        type: 'select',
        required: true,
        options: cashFlowReferenceOptions,
      },
      { key: 'referenceId', label: 'Referência ID', type: 'text', required: true },
      { key: 'amount', label: 'Valor', type: 'number', required: true, min: 0.01 },
      { key: 'type', label: 'Tipo', type: 'select', required: true, options: cashFlowTypeOptions },
      { key: 'date', label: 'Data', type: 'datetime' },
      { key: 'description', label: 'Descrição', type: 'textarea' },
    ],
  },
  {
    key: 'suppliers',
    section: 'financial',
    title: 'Fornecedores',
    subtitle: 'Cadastro mestre financeiro',
    routePath: '/app/financial/master/suppliers',
    icon: 'mdi-domain',
    basePath: '/financial/master/suppliers',
    moduleAccess: 'financial',
    permissions: {
      read: 'financial.master.read',
      create: 'financial.master.manage',
      update: 'financial.master.manage',
    },
    hideDelete: true,
    columns: [
      { key: 'name', title: 'Nome', path: 'name' },
      { key: 'documentNumber', title: 'Documento', path: 'documentNumber' },
      { key: 'email', title: 'E-mail', path: 'email' },
      { key: 'isActive', title: 'Ativo', path: 'isActive', type: 'boolean' },
    ],
    fields: [
      { key: 'name', label: 'Nome', type: 'text', required: true },
      { key: 'documentNumber', label: 'Documento', type: 'text', required: true },
      { key: 'email', label: 'E-mail', type: 'text' },
      { key: 'phone', label: 'Telefone', type: 'text' },
      { key: 'isActive', label: 'Ativo', type: 'switch' },
    ],
  },
  {
    key: 'customers',
    section: 'financial',
    title: 'Clientes',
    subtitle: 'Cadastro mestre financeiro',
    routePath: '/app/financial/master/customers',
    icon: 'mdi-account-multiple-outline',
    basePath: '/financial/master/customers',
    moduleAccess: 'financial',
    permissions: {
      read: 'financial.master.read',
      create: 'financial.master.manage',
      update: 'financial.master.manage',
    },
    hideDelete: true,
    columns: [
      { key: 'name', title: 'Nome', path: 'name' },
      { key: 'documentNumber', title: 'Documento', path: 'documentNumber' },
      { key: 'email', title: 'E-mail', path: 'email' },
      { key: 'isActive', title: 'Ativo', path: 'isActive', type: 'boolean' },
    ],
    fields: [
      { key: 'name', label: 'Nome', type: 'text', required: true },
      { key: 'documentNumber', label: 'Documento', type: 'text', required: true },
      { key: 'email', label: 'E-mail', type: 'text' },
      { key: 'phone', label: 'Telefone', type: 'text' },
      { key: 'isActive', label: 'Ativo', type: 'switch' },
    ],
  },
  {
    key: 'cost-centers',
    section: 'financial',
    title: 'Centros de Custo',
    subtitle: 'Cadastro mestre financeiro',
    routePath: '/app/financial/master/cost-centers',
    icon: 'mdi-tag-outline',
    basePath: '/financial/master/cost-centers',
    moduleAccess: 'financial',
    permissions: {
      read: 'financial.master.read',
      create: 'financial.master.manage',
      update: 'financial.master.manage',
    },
    hideDelete: true,
    columns: [
      { key: 'code', title: 'Código', path: 'code' },
      { key: 'name', title: 'Nome', path: 'name' },
      { key: 'isActive', title: 'Ativo', path: 'isActive', type: 'boolean' },
    ],
    fields: [
      { key: 'code', label: 'Código', type: 'text', required: true },
      { key: 'name', label: 'Nome', type: 'text', required: true },
      { key: 'description', label: 'Descrição', type: 'textarea' },
      { key: 'isActive', label: 'Ativo', type: 'switch' },
    ],
  },
  {
    key: 'categories',
    section: 'financial',
    title: 'Categorias Financeiras',
    subtitle: 'Cadastro mestre financeiro',
    routePath: '/app/financial/master/categories',
    icon: 'mdi-shape-outline',
    basePath: '/financial/master/categories',
    moduleAccess: 'financial',
    permissions: {
      read: 'financial.master.read',
      create: 'financial.master.manage',
      update: 'financial.master.manage',
    },
    hideDelete: true,
    columns: [
      { key: 'code', title: 'Código', path: 'code' },
      { key: 'name', title: 'Nome', path: 'name' },
      { key: 'type', title: 'Tipo', path: 'type', type: 'status' },
      { key: 'isActive', title: 'Ativo', path: 'isActive', type: 'boolean' },
    ],
    fields: [
      { key: 'code', label: 'Código', type: 'text', required: true },
      { key: 'name', label: 'Nome', type: 'text', required: true },
      { key: 'type', label: 'Tipo', type: 'select', required: true, options: categoryTypeOptions },
      { key: 'parentId', label: 'Categoria pai ID', type: 'text' },
      { key: 'isActive', label: 'Ativo', type: 'switch' },
    ],
  },
  {
    key: 'payment-methods',
    section: 'financial',
    title: 'Formas de Pagamento',
    subtitle: 'Cadastro mestre financeiro',
    routePath: '/app/financial/master/payment-methods',
    icon: 'mdi-credit-card-outline',
    basePath: '/financial/master/payment-methods',
    moduleAccess: 'financial',
    permissions: {
      read: 'financial.master.read',
      create: 'financial.master.manage',
      update: 'financial.master.manage',
    },
    hideDelete: true,
    columns: [
      { key: 'name', title: 'Nome', path: 'name' },
      { key: 'type', title: 'Tipo', path: 'type', type: 'status' },
      {
        key: 'allowsInstallments',
        title: 'Parcelado',
        path: 'allowsInstallments',
        type: 'boolean',
      },
      { key: 'isActive', title: 'Ativo', path: 'isActive', type: 'boolean' },
    ],
    fields: [
      { key: 'name', label: 'Nome', type: 'text', required: true },
      {
        key: 'type',
        label: 'Tipo',
        type: 'select',
        required: true,
        options: paymentMethodTypeOptions,
      },
      { key: 'allowsInstallments', label: 'Permite parcelamento', type: 'switch' },
      { key: 'isActive', label: 'Ativo', type: 'switch' },
    ],
  },
  {
    key: 'chart-accounts',
    section: 'financial',
    title: 'Plano de Contas',
    subtitle: 'Cadastro mestre financeiro',
    routePath: '/app/financial/master/chart-accounts',
    icon: 'mdi-book-open-variant-outline',
    basePath: '/financial/master/chart-accounts',
    moduleAccess: 'financial',
    permissions: {
      read: 'financial.master.read',
      create: 'financial.master.manage',
      update: 'financial.master.manage',
    },
    hideDelete: true,
    columns: [
      { key: 'code', title: 'Código', path: 'code' },
      { key: 'name', title: 'Nome', path: 'name' },
      { key: 'nature', title: 'Natureza', path: 'nature', type: 'status' },
      { key: 'isActive', title: 'Ativo', path: 'isActive', type: 'boolean' },
    ],
    fields: [
      { key: 'code', label: 'Código', type: 'text', required: true },
      { key: 'name', label: 'Nome', type: 'text', required: true },
      {
        key: 'nature',
        label: 'Natureza',
        type: 'select',
        required: true,
        options: chartAccountNatureOptions,
      },
      { key: 'parentId', label: 'Conta pai ID', type: 'text' },
      { key: 'isActive', label: 'Ativo', type: 'switch' },
    ],
  },
  {
    key: 'recurrence-rules',
    section: 'financial',
    title: 'Regras de Recorrência',
    subtitle: 'Cadastro mestre financeiro',
    routePath: '/app/financial/master/recurrence-rules',
    icon: 'mdi-repeat-variant',
    basePath: '/financial/master/recurrence-rules',
    moduleAccess: 'financial',
    permissions: {
      read: 'financial.master.read',
      create: 'financial.master.manage',
      update: 'financial.master.manage',
    },
    hideDelete: true,
    columns: [
      { key: 'name', title: 'Nome', path: 'name' },
      { key: 'frequency', title: 'Frequência', path: 'frequency', type: 'status' },
      { key: 'intervalCount', title: 'Intervalo', path: 'intervalCount' },
      { key: 'isActive', title: 'Ativo', path: 'isActive', type: 'boolean' },
    ],
    fields: [
      { key: 'name', label: 'Nome', type: 'text', required: true },
      {
        key: 'frequency',
        label: 'Frequência',
        type: 'select',
        required: true,
        options: recurrenceFrequencyOptions,
      },
      { key: 'intervalCount', label: 'Intervalo', type: 'number', min: 1, max: 24 },
      { key: 'dayOfMonth', label: 'Dia do mês', type: 'number', min: 1, max: 31 },
      { key: 'endDate', label: 'Fim', type: 'date' },
      { key: 'maxOccurrences', label: 'Máx. ocorrências', type: 'number', min: 1, max: 240 },
      { key: 'isActive', label: 'Ativo', type: 'switch' },
    ],
  },
  {
    key: 'interest-fine-rules',
    section: 'financial',
    title: 'Regras de Juros/Multa',
    subtitle: 'Cadastro mestre financeiro',
    routePath: '/app/financial/master/interest-fine-rules',
    icon: 'mdi-percent-outline',
    basePath: '/financial/master/interest-fine-rules',
    moduleAccess: 'financial',
    permissions: {
      read: 'financial.master.read',
      create: 'financial.master.manage',
      update: 'financial.master.manage',
    },
    hideDelete: true,
    columns: [
      { key: 'name', title: 'Nome', path: 'name' },
      { key: 'monthlyInterestRate', title: 'Juros %', path: 'monthlyInterestRate' },
      { key: 'finePercentage', title: 'Multa %', path: 'finePercentage' },
      { key: 'graceDays', title: 'Carência', path: 'graceDays' },
      { key: 'isActive', title: 'Ativo', path: 'isActive', type: 'boolean' },
    ],
    fields: [
      { key: 'name', label: 'Nome', type: 'text', required: true },
      {
        key: 'monthlyInterestRate',
        label: 'Juros mensal %',
        type: 'number',
        required: true,
        min: 0,
        max: 100,
      },
      { key: 'finePercentage', label: 'Multa %', type: 'number', required: true, min: 0, max: 100 },
      {
        key: 'graceDays',
        label: 'Dias de carência',
        type: 'number',
        required: true,
        min: 0,
        max: 365,
      },
      { key: 'isActive', label: 'Ativo', type: 'switch' },
    ],
  },
]

export const reports: ReportDefinition[] = [
  {
    key: 'financial-report-cashflow',
    title: 'Relatório de Fluxo de Caixa',
    routePath: '/app/financial/reports/cash-flow',
    endpoint: '/financial/reports/cash-flow',
    permission: 'financial.reports.read',
    moduleAccess: 'financial',
    filters: [
      { key: 'from', label: 'De', type: 'date' },
      { key: 'to', label: 'Até', type: 'date' },
      { key: 'costCenterId', label: 'Centro de custo', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: financialStatusOptions },
    ],
  },
  {
    key: 'financial-report-overdue',
    title: 'Relatório de Vencidos',
    routePath: '/app/financial/reports/overdue',
    endpoint: '/financial/reports/overdue',
    permission: 'financial.reports.read',
    moduleAccess: 'financial',
    filters: [
      { key: 'from', label: 'De', type: 'date' },
      { key: 'to', label: 'Até', type: 'date' },
      { key: 'costCenterId', label: 'Centro de custo', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: financialStatusOptions },
    ],
  },
  {
    key: 'financial-report-dashboard',
    title: 'Dashboard Financeiro',
    routePath: '/app/financial/reports/dashboard',
    endpoint: '/financial/reports/dashboard',
    permission: 'financial.dashboard.read',
    moduleAccess: 'financial',
    filters: [
      { key: 'from', label: 'De', type: 'date' },
      { key: 'to', label: 'Até', type: 'date' },
      { key: 'costCenterId', label: 'Centro de custo', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: financialStatusOptions },
    ],
  },
  {
    key: 'financial-report-shipment-profitability',
    title: 'Rentabilidade por Shipment',
    routePath: '/app/financial/reports/shipment-profitability',
    endpoint: '/financial/reports/shipment-profitability',
    permission: 'financial.dashboard.read',
    moduleAccess: 'financial',
    filters: [
      { key: 'from', label: 'De', type: 'date' },
      { key: 'to', label: 'Até', type: 'date' },
      { key: 'status', label: 'Status', type: 'select', options: shipmentStatusOptions },
      { key: 'driverId', label: 'Motorista', type: 'text' },
      { key: 'vehicleId', label: 'Veículo', type: 'text' },
      { key: 'routeId', label: 'Rota', type: 'text' },
      { key: 'fuelCostPerKm', label: 'Combustível/KM', type: 'text' },
      { key: 'tollCostPerKm', label: 'Pedágio/KM', type: 'text' },
    ],
  },
]

export function getResourceByKey(key: string): ResourceDefinition | undefined {
  return resources.find((item) => item.key === key)
}

export function getReportByKey(key: string): ReportDefinition | undefined {
  return reports.find((item) => item.key === key)
}
